/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nativeLib_Zbar */

#ifndef _Included_nativeLib_Zbar
#define _Included_nativeLib_Zbar
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nativeLib_Zbar
 * Method:    decode
 * Signature: (II[B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_nativeLib_Zbar_decode
  (JNIEnv *, jobject, jint, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
